from __future__ import annotations

TELEMETRY_SOURCE_VERSION = "study_buddy_v1"

VIDEO_LOOP_WINDOW_SECONDS = 15 * 60
VIDEO_LOOP_REPLAY_THRESHOLD = 3
VIDEO_LOOP_SEEK_BACK_THRESHOLD = 5

SUBMISSION_FAILURE_WINDOW_SECONDS = 10 * 60
SUBMISSION_FAILURE_THRESHOLD = 2

EDITOR_STALL_WINDOW_SECONDS = 7 * 60

QUIZ_GAP_MIN_DIRECT_CHECKS = 2
QUIZ_GAP_ACCURACY_THRESHOLD = 0.50

INTERVENTION_COOLDOWN_SECONDS = 20 * 60

REVIEW_STALENESS_WEIGHT = 0.50
REVIEW_SUPPORT_NEED_WEIGHT = 0.30
REVIEW_MASTERY_GAP_WEIGHT = 0.20
REVIEW_STALENESS_DAYS_THRESHOLD = 2
REVIEW_MASTERY_THRESHOLD = 0.70

PEDAGOGICAL_CONTEXT_TOKEN_BUDGET = 2500
LLM_TIMEOUT_SECONDS = 8
