include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - backend/**
    - frontend/build/**
    - frontend/.dart_tool/**

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
