// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Regenerate this file with:
///   flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run `flutterfire configure` to add support.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzP2Xx8uhYLuv07sFTIKImJj2iK3hN4UY',
    appId: '1:262941037092:web:1dc3da7c2e0281e8d9feb1',
    messagingSenderId: '262941037092',
    projectId: 'rlplat',
    authDomain: 'rlplat.firebaseapp.com',
    storageBucket: 'rlplat.firebasestorage.app',
    measurementId: 'G-7XGF0GN4RQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoOjzCIazcCgWe75PArGABJY_0swsK8KE',
    appId: '1:262941037092:ios:2c44364b5615739bd9feb1',
    messagingSenderId: '262941037092',
    projectId: 'rlplat',
    storageBucket: 'rlplat.firebasestorage.app',
    iosClientId:
        '262941037092-q6781hh5crfhn3c4j9j5shrccs911kln.apps.googleusercontent.com',
    iosBundleId: 'com.rlide.rlIde',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoOjzCIazcCgWe75PArGABJY_0swsK8KE',
    appId: '1:262941037092:ios:989f303f2cc7a322d9feb1',
    messagingSenderId: '262941037092',
    projectId: 'rlplat',
    storageBucket: 'rlplat.firebasestorage.app',
    iosClientId:
        '262941037092-fblaumn21pqnjgo5td99riev0jbpjdqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradProject-yousefG',
  );
}
