"""Manim scene helpers and demo scenes for concept videos."""

from .helpers import (
    CameraSpherePin,
    EquationTransformPlan,
    GridCell,
    IterableGrid,
    StaticTileAsset,
    create_iterable_grid,
    gymnasium_toy_text_asset_dir,
    highlight_animation,
    make_highlighter,
    resolve_asset_path,
    transform_equation_parts,
    traverse_grid,
)
from .panels import (
    BaseConceptScene,
    StatefulHighlighter,
    HighlightedAnimation,
    highlighted_animation,
    note_stack,
    panel,
    code_panel,
    equation_panel,
    environment_panel,
    blackjack_panel,
    cliffwalking_panel,
    FormulaStepper,
    frozenlake_frame,
    pill,
    ActionBarChart,
    SynchronizedFocusGroup,
    action_arrows_overlay,
    CodeStepper,
    zoom_to,
    zoom_reset,
    EnvironmentPanel,
    env_panel,
    card_mobject,
    # Color constants
    STATE_COLOR,
    VALUE_COLOR,
    REWARD_COLOR,
    PENALTY_COLOR,
    POLICY_COLOR,
    ACTION_COLOR,
    BG_COLOR,
    BG_PANEL,
    BG_GRID,
    CODE_ACCENT,
    # Legacy aliases
    ACCENT_BLUE,
    ACCENT_YELLOW,
    ACCENT_GREEN,
    ACCENT_SLATE,
    BG_DEEP,
    # Opacity constants
    OPACITY_PRIMARY,
    OPACITY_SECONDARY,
    OPACITY_BACKGROUND,
)

__all__ = [
    # helpers.py
    "CameraSpherePin",
    "EquationTransformPlan",
    "GridCell",
    "IterableGrid",
    "StaticTileAsset",
    "create_iterable_grid",
    "gymnasium_toy_text_asset_dir",
    "highlight_animation",
    "make_highlighter",
    "resolve_asset_path",
    "transform_equation_parts",
    "traverse_grid",
    # panels.py
    "BaseConceptScene",
    "StatefulHighlighter",
    "HighlightedAnimation",
    "highlighted_animation",
    "note_stack",
    "panel",
    "code_panel",
    "equation_panel",
    "environment_panel",
    "blackjack_panel",
    "cliffwalking_panel",
    "FormulaStepper",
    "frozenlake_frame",
    "pill",
    "ActionBarChart",
    "SynchronizedFocusGroup",
    "action_arrows_overlay",
    "CodeStepper",
    "zoom_to",
    "zoom_reset",
    "EnvironmentPanel",
    "env_panel",
    "card_mobject",
    "STATE_COLOR", "VALUE_COLOR", "REWARD_COLOR", "PENALTY_COLOR",
    "POLICY_COLOR", "ACTION_COLOR", "BG_COLOR", "BG_PANEL", "BG_GRID",
    "CODE_ACCENT",
    "ACCENT_BLUE", "ACCENT_YELLOW", "ACCENT_GREEN", "ACCENT_SLATE", "BG_DEEP",
    "OPACITY_PRIMARY", "OPACITY_SECONDARY", "OPACITY_BACKGROUND",
]
